# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa3ecdfeffa5d50f570257500ef0e350604b252069c95269eda22c7d8cf7a0ff62f668e00d8568ae9ee083fc6a565d071dffa5c713f6c0e00572d83cc35dd9fc

test:
  secret_key_base: 7be7c024a0ee71e5d2491a85edb2f417b827aec4657b1148251db1ea10a55afae8a784c237f32b508b1705d299de8a6a389585cbd9c715d3e9ca97d16758c0b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
